site_name: Chassis Documentation
site_url: https://your-username.github.io/chassis/

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy

# This tells MkDocs where to find your Markdown files
docs_dir: documentation


# How your navigation sidebar will be structured
nav:
  - 'Quick Start': '00_quick_start.md'
  - 'Domain Concepts': '01_domain_concepts.md'
  - 'View Concepts': '02_view_concepts.md'
  - 'Project Structure': '03_project_organisation.md'
  - 'Naming Conventions': '04_naming_convention.md'
  - 'Practical Guides':
    - 'Writing Business Logic': '05_business_logic_guide.md'
    - 'Writing ViewModels': '06_view_model_guide.md'
    - 'View Integration': '07_view_integration_guide.md'