name: chassis_builder
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.0.0
  code_builder: ^4.10.0
  dart_style: ^2.3.0
  glob: ^2.1.2
  path: ^1.9.0
  chassis:
    path: ../chassis

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
